# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0544f3fdf69011864e0a710a695f19f0d5b16b14c34343ce76317229991639230dba758f1fbe5f8222103492be3df642fe1dd6ffc2da012ff1a9e7c932e5113

test:
  secret_key_base: b24aac9b85402d3875cc624a892442082aab65334b9c5aee68e2a174ec3a585484f3f7ebdd11be56ca7d78397b9cbe6b99ee77781db3ee569961d2b1aae646d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
